export const types = Object.freeze({
  SET_FETCH_SIGN_IN_REQUEST: 'SET_FETCH_SIGN_IN_REQUEST',
  SET_FETCH_SIGN_IN_SUCCESS: 'SET_FETCH_SIGN_IN_SUCCESS',
  SET_FETCH_SIGN_IN_ERROR: 'SET_FETCH_SIGN_IN_ERROR',

  SET_FETCH_PROFILE_REQUEST: 'SET_FETCH_PROFILE_REQUEST',
  SET_FETCH_PROFILE_SUCCESS: 'SET_FETCH_PROFILE_SUCCESS',
  SET_FETCH_PROFILE_ERROR: 'SET_FETCH_PROFILE_ERROR',
});
